### ISSUE TITLE
404 not found on login

### ISSUE THREAD

**Issue by ljhardy** [andrefigueira/memcache-monitor#2]
Does the .htaccess file work with nginx?

**Comment by ljhardy** [comment]
Never mind, nginx does not support .htaccess files.  So I think that this solution will only work wth Apache?

**Comment by andrefigueira** [comment]
Hi there!

No, .htaccess is Apache specific - also, this was written a really long time ago, so I'll probably add a note that it's not maintained any more, feel free to fork and modify as much as you want, you'll be able to get it to work with nginx, as the code itself is not Apache specific.

**Comment by ra100** [comment]
And I've just made it work on nginx :)

anyway @ljhardy if you want to make it work on nginx, just add to your configuration something like this:

``` nginx
    location /memcache-monitor {
        rewrite ^(.+)/request/([^/.]+)/$ $1/lib/request-handler.php?function=$2;
        rewrite ^(.+)/status-board$ $1/status-board.php;
    }
```

**Comment by ljhardy** [comment]
Thanks!!

---

Len Hardy
Bartlett, IL. USA
http://www.firehole.us
http://www.lenhardy.com
